let mapleader = " "

" Shamelessly copied from Chris Toomey
" https://github.com/christoomey/dotfiles/blob/master/vim/vimrc

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

"  Plugins
call plug#begin()
call s:SourceConfigFilesIn('rcplugins')
call plug#end()

filetype plugin indent on
inoremap jj <Esc>
nnoremap ; :

syntax on
filetype indent plugin on
call s:SourceConfigFilesIn('rcfiles')

"  Set path for `find` awesomeness
set path+=**
set wildmenu

"  Use the old regex engine, which for some reason works better at parsing
"  ruby syntax highlighting
set re=1
