dotdir=$(dirname $(readlink ~/.zshrc))

source "$dotdir/aliases.zsh"
source "$dotdir/key-bindings.zsh"
source "$dotdir/vi-mode.zsh"
source "$dotdir/functions.zsh"
source "$dotdir/options.zsh"


# Virtual env wrapper
source /usr/local/bin/virtualenvwrapper.sh

# Autoenv
source /usr/local/opt/autoenv/activate.sh

function git_prompt() {
  if [[ $(git status 2>/dev/null) > 0 ]]; then
   echo "on branch $(git rev-parse --abbrev-ref HEAD)" 
  else
    echo ""
  fi
}

function lprompt(){
  if [[ $? == 0 ]]; then
    echo "\e[32mon %w at %t in %d: " 
  else
    echo "\e[31mon %w at %t in %d: "
  fi
}

PROMPT='$(lprompt)'
RPROMPT='$(git_prompt)'
export GOPATH='/Users/jturner/dev/golang/bin'
export PATH=$PATH:$GOPATH
export PATH="/usr/local/sbin:$PATH"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

