export ZSH_DISABLE_COMPFIX=true
dotdir="$(dirname "$(readlink ~/.zshrc)")"

source "$dotdir/aliases.zsh"
source "$dotdir/key-bindings.zsh"
source "$dotdir/vi-mode.zsh"
source "$dotdir/functions.zsh"
source "$dotdir/options.zsh"

autoload -U colors && colors

# No arguments: `git status`
# With arguments: acts like `git`
g() {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status
  fi
}

autoload -U promptinit
promptinit

export PATH="/usr/local/go/bin:$PATH"
export GOPATH="$HOME/code"
export PATH="$PATH:$GOPATH/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:$dotdir/scripts"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/npm-global/bin"

# Get zsh functions (there's a better way to do this probably)
# Mac
[[ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# Linux
[[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Source completions
fpath=(/usr/local/share/zsh-completions $fpath)

if [[ $(uname) == 'Darwin' ]]; then
  [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
else
  source /usr/share/autojump/autojump.sh
fi

autoload -U +X compinit && compinit -i
autoload -U +X bashcompinit && bashcompinit
find /usr/local/etc/bash_completion.d -type f -exec source {} \;

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules,.idea,.gradle}/*" 2>/dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
bindkey -s '^p' 'vim $(fzf)^M'
export HOMEBREW_NO_AUTOUPDATE=1

alias k='kubectl'
alias kc='kubectx $(kubectx | fzf)'
alias 'kc?'='kubectx'
alias kns='kubens $(kubens | fzf)'
alias 'kns?'='kubens'

export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

export PATH="$HOME/.local/bin:$PATH"

eval "$(starship init zsh)"

# finally, do anything specific to this machine
source "$HOME/.machinerc"
