dotdir=$(dirname $(readlink ~/.zshrc))

source "$dotdir/aliases.zsh"
source "$dotdir/key-bindings.zsh"
source "$dotdir/vi-mode.zsh"
source "$dotdir/functions.zsh"
source "$dotdir/options.zsh"


# Virtual env wrapper
source /usr/local/bin/virtualenvwrapper.sh

# Autoenv
source /usr/local/opt/autoenv/activate.sh

RPROMPT="$(git rev-parse --abbrev-ref HEAD)"
PROMPT="in ${PWD/#$HOME/~} "
export GOPATH='/Users/jturner/dev/golang/bin'
export PATH=$PATH:$GOPATH
export PATH="/usr/local/sbin:$PATH"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

